<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messaging.proto

namespace GPBMetadata;

class Messaging
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae2010a0f6d6573736167696e672e70726f746f12096d6573736167696e67222a0a0b53656e6452657175657374120a0a02746f180120012809120f0a076d657373616765180220012809220e0a0c53656e64526573706f6e736532440a094d6573736167696e6712370a0453656e6412162e6d6573736167696e672e53656e64526571756573741a172e6d6573736167696e672e53656e64526573706f6e7365423a5a386769742e646f6c616e736f66742e6f72672f65676f692f6b6579626173652d6c6d74702d676c75652f70726f746f2f6d6573736167696e67620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

