<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messaging.proto

namespace Messaging;

/**
 * Generated from protobuf message <code>messaging.SendResponse</code>
 */
class SendResponse extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Messaging::initOnce();
        parent::__construct($data);
    }

}

